version: '3'

services:
  php-web:
    build: docker
    ports:
      - "8080:80"
    volumes:
      - "./app:/var/www"
      - "./docker/php.ini:/usr/local/etc/php/php.ini"
    links:
      - mariadb
  mariadb:
    image: mariadb:10.6.12
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "./docker/mariadb-data:/var/lib/mysql"
      - "./docker/iceCream.sql:/docker-entrypoint-initdb.d/dump.sql"
    environment:
      - MARIADB_ROOT_PASSWORD=Azerty123
      - LANG=C.UTF-8
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=50M
    restart: always
    depends_on:
      - mariadb